#!/usr/bin/env python3
#Project Euler - Problem 67 - http://projecteuler.net

alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

with open("names.txt") as f:
    for line in f:
        names = list(eval(line))

names.sort()

for i in range(len(names)):


