#!/usr/bin/env python3
# Project Euler - Problem 25 - http://projecteuler.net

class Fib:
    '''Iterator that will yield the entire Fibonacci series;
          if you'd only give it the chance'''

    def __init__(self):
        pass

    def __iter__(self):
        self.a = 1
        self.b = 1
        self.count = 1

    def __next__(self):
        fib = self.a
        self.a, self.b = self.b, self.a + self.b
        self.count += 1
        return fib

fib = Fib()
fib.__iter__()
fib.__next__()

while True:
    if len(str(fib.a)) == 1000:
        break
    else:
        next(fib)

print("The first number in the Fibonacci series with 1000 digits is", 
        fib.a, "which is the", fib.count, "number in the series.")
