#!/usr/bin/env python3
#Project Euler - Problem 17 - http://projecteuler.net
#
numbers = { 0:'', 1:'one', 2:'two', 3:'three', 4:'four', 5:'five', 6:'six', 7:'seven', 8:'eight', 9:'nine', 10:'ten', 11:'eleven', 12:'twelve', 13:'thirteen', 14:'fourteen', 15:'fifteen', 16:'sixteen', 17:'seventeen', 18:'eighteen', 19:'nineteen', 20:'twenty', 30:'thirty', 40:'forty', 50:'fifty', 60:'sixty', 70:'seventy', 80:'eighty', 90:'ninety', 100:'hundred'}

def nwords(n):
    n = str(n)
    if len(n) == 1:
        return (numbers[int(n)])
    if len(n) == 2:
        return (numbers[int(n[-2])*10] + numbers[int(n[-1])])
    if len(n) == 3:
        if n[-2:] == '00':
            return (numbers[int(n[-3])] + 'hundred')
        else:
            return (numbers[int(n[-3])] + 'hundredand' + numbers[int(n[-2])*10] + numbers[int(n[-1])])
