#!/usr/bin/env python3
#Project Euler - Problem 23 - http://projecteuler.net
def prop_div(n):
    '''Returns proper divisors of n as a set.'''
    return {i for i in range(1, n//2+1) if n % i == 0}


