#!/usr/bin/env python3
# Project Euler - Problem 24 - http://projecteuler.net
import itertools

gen = itertools.permutations(range(10))
count = 0

while True:
    count += 1
    if count == 1000000:
        print(str(next(gen)).strip(', '))
        break
    else:
        next(gen)
